#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Tweet Delete', '0.1');
$app->add(new \Tweets\DeleteCommand());
$app->add(new \Tweets\DeleteLikesCommand());

$app->run();